name: tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14', '1.15', '1.16' ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # need tags for `git describe`

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: make

      - name: Test
        run: make check
