name: tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14', '1.15', '1.16' ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # need tags for `git describe`

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: make

      - name: Test
        run: make check

      - name: Translate coverage report
        uses: jandelgado/gcov2lcov-action@v1.0.8
        with:
          infile: test/cov.cov
          outfile: test/cov.lcov

      - name: Submit coverage report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: test/cov.lcov
          flag-name: go-${{ matrix.go }}
          parallel: true

  finish:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Finalize coverage report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
